/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWorkflowRunsRouteImport } from './routes/api/workflow-runs'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiPlaygroundRunsRouteImport } from './routes/api/playground-runs'
import { Route as PathlessLayoutNestedLayoutRouteImport } from './routes/_pathlessLayout/_nested-layout'
import { Route as ApiWorkflowRunsIdRouteImport } from './routes/api/workflow-runs.$id'
import { Route as ApiUsersIdRouteImport } from './routes/api/users.$id'
import { Route as ApiDbHealthRouteImport } from './routes/api/db/health'
import { Route as PathlessLayoutNestedLayoutRouteBRouteImport } from './routes/_pathlessLayout/_nested-layout/route-b'
import { Route as PathlessLayoutNestedLayoutRouteARouteImport } from './routes/_pathlessLayout/_nested-layout/route-a'

const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowRunsRoute = ApiWorkflowRunsRouteImport.update({
  id: '/api/workflow-runs',
  path: '/api/workflow-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlaygroundRunsRoute = ApiPlaygroundRunsRouteImport.update({
  id: '/api/playground-runs',
  path: '/api/playground-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRoute =
  PathlessLayoutNestedLayoutRouteImport.update({
    id: '/_nested-layout',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const ApiWorkflowRunsIdRoute = ApiWorkflowRunsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiWorkflowRunsRoute,
} as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiDbHealthRoute = ApiDbHealthRouteImport.update({
  id: '/api/db/health',
  path: '/api/db/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRouteBRoute =
  PathlessLayoutNestedLayoutRouteBRouteImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const PathlessLayoutNestedLayoutRouteARoute =
  PathlessLayoutNestedLayoutRouteARouteImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deferred': typeof DeferredRoute
  '/api/playground-runs': typeof ApiPlaygroundRunsRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/api/workflow-runs': typeof ApiWorkflowRunsRouteWithChildren
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/db/health': typeof ApiDbHealthRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/workflow-runs/$id': typeof ApiWorkflowRunsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deferred': typeof DeferredRoute
  '/api/playground-runs': typeof ApiPlaygroundRunsRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/api/workflow-runs': typeof ApiWorkflowRunsRouteWithChildren
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/db/health': typeof ApiDbHealthRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/workflow-runs/$id': typeof ApiWorkflowRunsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/deferred': typeof DeferredRoute
  '/_pathlessLayout/_nested-layout': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/api/playground-runs': typeof ApiPlaygroundRunsRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/api/workflow-runs': typeof ApiWorkflowRunsRouteWithChildren
  '/_pathlessLayout/_nested-layout/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/_pathlessLayout/_nested-layout/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/db/health': typeof ApiDbHealthRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/workflow-runs/$id': typeof ApiWorkflowRunsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deferred'
    | '/api/playground-runs'
    | '/api/users'
    | '/api/workflow-runs'
    | '/route-a'
    | '/route-b'
    | '/api/db/health'
    | '/api/users/$id'
    | '/api/workflow-runs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deferred'
    | '/api/playground-runs'
    | '/api/users'
    | '/api/workflow-runs'
    | '/route-a'
    | '/route-b'
    | '/api/db/health'
    | '/api/users/$id'
    | '/api/workflow-runs/$id'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/deferred'
    | '/_pathlessLayout/_nested-layout'
    | '/api/playground-runs'
    | '/api/users'
    | '/api/workflow-runs'
    | '/_pathlessLayout/_nested-layout/route-a'
    | '/_pathlessLayout/_nested-layout/route-b'
    | '/api/db/health'
    | '/api/users/$id'
    | '/api/workflow-runs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  DeferredRoute: typeof DeferredRoute
  ApiPlaygroundRunsRoute: typeof ApiPlaygroundRunsRoute
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  ApiWorkflowRunsRoute: typeof ApiWorkflowRunsRouteWithChildren
  ApiDbHealthRoute: typeof ApiDbHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflow-runs': {
      id: '/api/workflow-runs'
      path: '/api/workflow-runs'
      fullPath: '/api/workflow-runs'
      preLoaderRoute: typeof ApiWorkflowRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/playground-runs': {
      id: '/api/playground-runs'
      path: '/api/playground-runs'
      fullPath: '/api/playground-runs'
      preLoaderRoute: typeof ApiPlaygroundRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout': {
      id: '/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/api/workflow-runs/$id': {
      id: '/api/workflow-runs/$id'
      path: '/$id'
      fullPath: '/api/workflow-runs/$id'
      preLoaderRoute: typeof ApiWorkflowRunsIdRouteImport
      parentRoute: typeof ApiWorkflowRunsRoute
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/db/health': {
      id: '/api/db/health'
      path: '/api/db/health'
      fullPath: '/api/db/health'
      preLoaderRoute: typeof ApiDbHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout/route-b': {
      id: '/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/route-b'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteBRouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/_pathlessLayout/_nested-layout/route-a': {
      id: '/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/route-a'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteARouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
  }
}

interface PathlessLayoutNestedLayoutRouteChildren {
  PathlessLayoutNestedLayoutRouteARoute: typeof PathlessLayoutNestedLayoutRouteARoute
  PathlessLayoutNestedLayoutRouteBRoute: typeof PathlessLayoutNestedLayoutRouteBRoute
}

const PathlessLayoutNestedLayoutRouteChildren: PathlessLayoutNestedLayoutRouteChildren =
  {
    PathlessLayoutNestedLayoutRouteARoute:
      PathlessLayoutNestedLayoutRouteARoute,
    PathlessLayoutNestedLayoutRouteBRoute:
      PathlessLayoutNestedLayoutRouteBRoute,
  }

const PathlessLayoutNestedLayoutRouteWithChildren =
  PathlessLayoutNestedLayoutRoute._addFileChildren(
    PathlessLayoutNestedLayoutRouteChildren,
  )

interface PathlessLayoutRouteChildren {
  PathlessLayoutNestedLayoutRoute: typeof PathlessLayoutNestedLayoutRouteWithChildren
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutNestedLayoutRoute: PathlessLayoutNestedLayoutRouteWithChildren,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

interface ApiUsersRouteChildren {
  ApiUsersIdRoute: typeof ApiUsersIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersIdRoute: ApiUsersIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

interface ApiWorkflowRunsRouteChildren {
  ApiWorkflowRunsIdRoute: typeof ApiWorkflowRunsIdRoute
}

const ApiWorkflowRunsRouteChildren: ApiWorkflowRunsRouteChildren = {
  ApiWorkflowRunsIdRoute: ApiWorkflowRunsIdRoute,
}

const ApiWorkflowRunsRouteWithChildren = ApiWorkflowRunsRoute._addFileChildren(
  ApiWorkflowRunsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  DeferredRoute: DeferredRoute,
  ApiPlaygroundRunsRoute: ApiPlaygroundRunsRoute,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  ApiWorkflowRunsRoute: ApiWorkflowRunsRouteWithChildren,
  ApiDbHealthRoute: ApiDbHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
